#!/usr/bin/env bash
# generate-day49-audio.sh
# Generates Day 49 EN + FR audio via fal.ai MiniMax Speech-02 Turbo,
# uploads to Convex PROD (laudable-hedgehog-797),
# then dual-writes the same MP3 bytes to Convex DEV (neat-frog-379).
#
# EN: single chunk (3766 chars)
# FR: single chunk (4625 chars)
# No ffmpeg concat needed.
#
# Prerequisites:
#   - FAL_KEY in .env.local (account must have balance)
#   - CONVEX_URL_AUDIO in .env.local (prod URL; falls back to NEXT_PUBLIC_CONVEX_URL)
#   - Text files pre-generated by audio-prep.py at /tmp/day-49-{en,fr}.txt
#
# Usage: bash scripts/generate-day49-audio.sh

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"

# Load env
source "$PROJECT_DIR/.env.local"

FAL_KEY="${FAL_KEY:?FAL_KEY not set}"
# Audio uploads target PROD explicitly. perfectaiagent.xyz reads from PROD;
# writing to DEV (neat-frog-379) makes audio invisible to users (Days 35-46 bug, 2026-04-09 → 2026-04-22).
CONVEX_URL="${CONVEX_URL_AUDIO:-${NEXT_PUBLIC_CONVEX_URL:?CONVEX_URL_AUDIO or NEXT_PUBLIC_CONVEX_URL must be set}}"
echo "[audio] Writing audio to PROD deployment: $CONVEX_URL"

EN_TEXT="/tmp/day-49-en.txt"
FR_TEXT="/tmp/day-49-fr.txt"

# Check preprocessed text files exist
for f in "$EN_TEXT" "$FR_TEXT"; do
  if [ ! -f "$f" ]; then
    echo "ERROR: Missing text file $f"
    echo "Run: python3 scripts/audio-prep.py content/en/diary/day-49.mdx en /tmp/day-49-en.txt"
    echo "     python3 scripts/audio-prep.py content/fr/diary/day-49.mdx fr /tmp/day-49-fr.txt"
    exit 1
  fi
done

generate_audio() {
  local text_file="$1"
  local voice_id="$2"
  local lang="$3"
  local out_mp3="$4"
  local label="$5"

  echo "Generating $label..."

  PAYLOAD=$(python3 - "$text_file" "$voice_id" "$lang" <<'PYEOF'
import json, sys
text_file, voice_id, lang = sys.argv[1], sys.argv[2], sys.argv[3]
with open(text_file) as f:
    text = f.read()
print(json.dumps({"text": text, "voice_id": voice_id, "language": lang}))
PYEOF
)

  RESPONSE=$(curl -s -X POST "https://fal.run/fal-ai/minimax/speech-02-turbo" \
    -H "Authorization: Key $FAL_KEY" \
    -H "Content-Type: application/json" \
    -d "$PAYLOAD")

  if echo "$RESPONSE" | python3 -c "import json,sys; d=json.load(sys.stdin); exit(0 if 'audio' in d or 'audio_url' in d else 1)" 2>/dev/null; then
    AUDIO_URL=$(echo "$RESPONSE" | python3 -c "import json,sys; d=json.load(sys.stdin); print(d.get('audio', {}).get('url', '') or d.get('audio_url', ''))")
    echo "  -> $AUDIO_URL"
    curl -s -o "$out_mp3" "$AUDIO_URL"
    echo "  Saved $out_mp3 ($(wc -c < "$out_mp3") bytes)"
  else
    echo "ERROR generating $label:"
    echo "$RESPONSE"
    exit 1
  fi
}

# --- Generate EN (single chunk) ---
generate_audio "$EN_TEXT" "English_Trustworthy_Man" "en" "/tmp/day-49-en.mp3" "EN day-49"

# --- Generate FR (single chunk) ---
generate_audio "$FR_TEXT" "French_Elegant_Man" "fr" "/tmp/day-49-fr.mp3" "FR day-49"

# --- Upload to Convex PROD ---
echo ""
echo "Uploading to Convex PROD ($CONVEX_URL)..."

upload_to_convex() {
  local mp3_file="$1"
  local slug="$2"
  local locale="$3"
  local target_url="$4"

  # Get upload URL
  UPLOAD_URL=$(curl -s -X POST "$target_url/api/mutation" \
    -H "Content-Type: application/json" \
    -d '{"path": "audio:generateUploadUrl", "args": {}, "format": "json"}' | python3 -c "import json,sys; print(json.load(sys.stdin)['value'])")

  echo "Upload URL for $slug/$locale: $UPLOAD_URL"

  # Upload file
  STORAGE_RESP=$(curl -s -X POST "$UPLOAD_URL" \
    -H "Content-Type: audio/mpeg" \
    --data-binary "@$mp3_file")

  STORAGE_ID=$(echo "$STORAGE_RESP" | python3 -c "import json,sys; print(json.load(sys.stdin)['storageId'])")
  echo "  storageId: $STORAGE_ID"

  # Save record
  SAVE_PAYLOAD=$(python3 - "$slug" "$locale" "$STORAGE_ID" <<'PYEOF'
import json, sys
slug, locale, storage_id = sys.argv[1], sys.argv[2], sys.argv[3]
print(json.dumps({
    "path": "audio:saveAudioFile",
    "args": {
        "slug": slug,
        "locale": locale,
        "storageId": storage_id,
        "filename": f"{slug}-{locale}.mp3"
    },
    "format": "json"
}))
PYEOF
)

  curl -s -X POST "$target_url/api/mutation" \
    -H "Content-Type: application/json" \
    -d "$SAVE_PAYLOAD" | python3 -c "import json,sys; print('  Saved ID:', json.load(sys.stdin).get('value'))"

  # Get public URL
  URL_PAYLOAD=$(python3 - "$slug" "$locale" <<'PYEOF'
import json, sys
slug, locale = sys.argv[1], sys.argv[2]
print(json.dumps({"path": "audio:getAudioUrl", "args": {"slug": slug, "locale": locale}, "format": "json"}))
PYEOF
)

  PUBLIC_URL=$(curl -s -X POST "$target_url/api/query" \
    -H "Content-Type: application/json" \
    -d "$URL_PAYLOAD" | python3 -c "import json,sys; print(json.load(sys.stdin).get('value'))")

  echo "  Public URL: $PUBLIC_URL"
}

upload_to_convex "/tmp/day-49-en.mp3" "day-49" "en" "$CONVEX_URL"
upload_to_convex "/tmp/day-49-fr.mp3" "day-49" "fr" "$CONVEX_URL"

echo ""
echo "PROD upload complete."

# --- Dual-write: upload same MP3 bytes to Convex DEV ---
echo ""
echo "Dual-write: uploading same MP3 bytes to Convex DEV (neat-frog-379)..."
echo "Zero additional fal.ai cost — reusing /tmp/day-49-{en,fr}.mp3"

cd "$PROJECT_DIR"
npx tsx scripts/upload-day49-to-dev.mts

echo ""
echo "Done. Both PROD (laudable-hedgehog-797) and DEV (neat-frog-379) have day-49/en and day-49/fr."
echo "Diary page serves audio by slug via audio:getAudioUrl — no MDX changes needed."
