#!/usr/bin/env bash
# generate-day42-audio.sh
# Generates Day 42 EN + FR audio via fal.ai MiniMax Speech-02 Turbo,
# concatenates chunks, uploads to Convex dev (neat-frog-379).
#
# EN: 3 chunks (chunk1, chunk2a, chunk2b) — chunk2 exceeded 5000-char API limit
# FR: 3 chunks (chunk1, chunk2, chunk3)
#
# Prerequisites:
#   - FAL_KEY in .env.local (account must have balance)
#   - ffmpeg installed
#   - NEXT_PUBLIC_CONVEX_URL in .env.local
#   - Chunk files pre-generated by audio-prep.py + split script
#
# Usage: bash scripts/generate-day42-audio.sh

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"

# Load env
source "$PROJECT_DIR/.env.local"

FAL_KEY="${FAL_KEY:?FAL_KEY not set}"
CONVEX_URL="${NEXT_PUBLIC_CONVEX_URL:?NEXT_PUBLIC_CONVEX_URL not set}"

EN_CHUNK1="/tmp/day-42-en-chunk1.txt"
EN_CHUNK2A="/tmp/day-42-en-chunk2a.txt"
EN_CHUNK2B="/tmp/day-42-en-chunk2b.txt"
FR_CHUNK1="/tmp/day-42-fr-chunk1.txt"
FR_CHUNK2="/tmp/day-42-fr-chunk2.txt"
FR_CHUNK3="/tmp/day-42-fr-chunk3.txt"

# Check preprocessed chunks exist
for f in "$EN_CHUNK1" "$EN_CHUNK2A" "$EN_CHUNK2B" "$FR_CHUNK1" "$FR_CHUNK2" "$FR_CHUNK3"; do
  if [ ! -f "$f" ]; then
    echo "ERROR: Missing chunk file $f"
    echo "Run audio-prep.py then split manually (see Day 41 for reference pattern)"
    exit 1
  fi
done

generate_chunk() {
  local text_file="$1"
  local voice_id="$2"
  local lang="$3"
  local out_mp3="$4"
  local label="$5"

  echo "Generating $label..."

  PAYLOAD=$(python3 - "$text_file" "$voice_id" "$lang" <<'PYEOF'
import json, sys
text_file, voice_id, lang = sys.argv[1], sys.argv[2], sys.argv[3]
with open(text_file) as f:
    text = f.read()
print(json.dumps({"text": text, "voice_id": voice_id, "language": lang}))
PYEOF
)

  RESPONSE=$(curl -s -X POST "https://fal.run/fal-ai/minimax/speech-02-turbo" \
    -H "Authorization: Key $FAL_KEY" \
    -H "Content-Type: application/json" \
    -d "$PAYLOAD")

  if echo "$RESPONSE" | python3 -c "import json,sys; d=json.load(sys.stdin); exit(0 if 'audio' in d or 'audio_url' in d else 1)" 2>/dev/null; then
    AUDIO_URL=$(echo "$RESPONSE" | python3 -c "import json,sys; d=json.load(sys.stdin); print(d.get('audio', {}).get('url', '') or d.get('audio_url', ''))")
    echo "  -> $AUDIO_URL"
    curl -s -o "$out_mp3" "$AUDIO_URL"
    echo "  Saved $out_mp3 ($(wc -c < "$out_mp3") bytes)"
  else
    echo "ERROR generating $label:"
    echo "$RESPONSE"
    exit 1
  fi
}

# --- EN chunks ---
generate_chunk "$EN_CHUNK1" "English_Trustworthy_Man" "en" "/tmp/day-42-en-c1.mp3" "EN chunk 1"
generate_chunk "$EN_CHUNK2A" "English_Trustworthy_Man" "en" "/tmp/day-42-en-c2a.mp3" "EN chunk 2a"
generate_chunk "$EN_CHUNK2B" "English_Trustworthy_Man" "en" "/tmp/day-42-en-c2b.mp3" "EN chunk 2b"

# Concat EN
echo "file '/tmp/day-42-en-c1.mp3'" > /tmp/day-42-en-list.txt
echo "file '/tmp/day-42-en-c2a.mp3'" >> /tmp/day-42-en-list.txt
echo "file '/tmp/day-42-en-c2b.mp3'" >> /tmp/day-42-en-list.txt
ffmpeg -y -f concat -safe 0 -i /tmp/day-42-en-list.txt -c copy /tmp/day-42-en.mp3
echo "EN concat done: $(ffprobe -v error -show_entries format=duration -of default=noprint_wrappers=1:nokey=1 /tmp/day-42-en.mp3 2>/dev/null)s"

# --- FR chunks ---
generate_chunk "$FR_CHUNK1" "French_Elegant_Man" "fr" "/tmp/day-42-fr-c1.mp3" "FR chunk 1"
generate_chunk "$FR_CHUNK2" "French_Elegant_Man" "fr" "/tmp/day-42-fr-c2.mp3" "FR chunk 2"
generate_chunk "$FR_CHUNK3" "French_Elegant_Man" "fr" "/tmp/day-42-fr-c3.mp3" "FR chunk 3"

# Concat FR
echo "file '/tmp/day-42-fr-c1.mp3'" > /tmp/day-42-fr-list.txt
echo "file '/tmp/day-42-fr-c2.mp3'" >> /tmp/day-42-fr-list.txt
echo "file '/tmp/day-42-fr-c3.mp3'" >> /tmp/day-42-fr-list.txt
ffmpeg -y -f concat -safe 0 -i /tmp/day-42-fr-list.txt -c copy /tmp/day-42-fr.mp3
echo "FR concat done: $(ffprobe -v error -show_entries format=duration -of default=noprint_wrappers=1:nokey=1 /tmp/day-42-fr.mp3 2>/dev/null)s"

# --- Upload to Convex ---
echo ""
echo "Uploading to Convex ($CONVEX_URL)..."

upload_to_convex() {
  local mp3_file="$1"
  local slug="$2"
  local locale="$3"

  # Get upload URL
  UPLOAD_URL=$(curl -s -X POST "$CONVEX_URL/api/mutation" \
    -H "Content-Type: application/json" \
    -d '{"path": "audio:generateUploadUrl", "args": {}, "format": "json"}' | python3 -c "import json,sys; print(json.load(sys.stdin)['value'])")

  echo "Upload URL for $slug/$locale: $UPLOAD_URL"

  # Upload file
  STORAGE_RESP=$(curl -s -X POST "$UPLOAD_URL" \
    -H "Content-Type: audio/mpeg" \
    --data-binary "@$mp3_file")

  STORAGE_ID=$(echo "$STORAGE_RESP" | python3 -c "import json,sys; print(json.load(sys.stdin)['storageId'])")
  echo "  storageId: $STORAGE_ID"

  # Save record
  SAVE_PAYLOAD=$(python3 - "$slug" "$locale" "$STORAGE_ID" <<'PYEOF'
import json, sys
slug, locale, storage_id = sys.argv[1], sys.argv[2], sys.argv[3]
print(json.dumps({
    "path": "audio:saveAudioFile",
    "args": {
        "slug": slug,
        "locale": locale,
        "storageId": storage_id,
        "filename": f"{slug}-{locale}.mp3"
    },
    "format": "json"
}))
PYEOF
)

  curl -s -X POST "$CONVEX_URL/api/mutation" \
    -H "Content-Type: application/json" \
    -d "$SAVE_PAYLOAD" | python3 -c "import json,sys; print('  Saved ID:', json.load(sys.stdin).get('value'))"

  # Get public URL
  URL_PAYLOAD=$(python3 - "$slug" "$locale" <<'PYEOF'
import json, sys
slug, locale = sys.argv[1], sys.argv[2]
print(json.dumps({"path": "audio:getAudioUrl", "args": {"slug": slug, "locale": locale}, "format": "json"}))
PYEOF
)

  PUBLIC_URL=$(curl -s -X POST "$CONVEX_URL/api/query" \
    -H "Content-Type: application/json" \
    -d "$URL_PAYLOAD" | python3 -c "import json,sys; print(json.load(sys.stdin).get('value'))")

  echo "  Public URL: $PUBLIC_URL"
}

upload_to_convex "/tmp/day-42-en.mp3" "day-42" "en"
upload_to_convex "/tmp/day-42-fr.mp3" "day-42" "fr"

echo ""
echo "Done. Diary page serves audio by slug via audio:getAudioUrl — no MDX changes needed."
